# Data Exploration

Training data is the historical dat I'm training on (cross-validation) and the actual temperature will be the testing data to test how effective the model is at predicting temperature. X is all the other factors, y is the temperature.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

def csv_read(filepath):
    """import csv file"""
    df = pd.read_csv(filepath)

    return df

def convert_date_time(df, col):
    df[col] = pd.to_datetime(col)
    return df

In [46]:
historical_preds = csv_read("/Users/jothigupta/sem_1/AIPI 520/weather-prediction-RDU/data/raw/NOAA_GFS_FORECAST_HISTORICAL.csv")
print(historical_preds.columns)
historical_preds.head()

historical_preds.head()
# Convert gfs_init_utc to datetime
historical_preds['gfs_init_utc'] = pd.to_datetime(historical_preds['gfs_init_utc'])

historical_preds.info()

# Split into X and y
X = historical_preds.drop(labels='gfs_temp_f', axis=1)
y = historical_preds['gfs_temp_f']

historical_preds.head()

cols = ['forecast_date', 'forecast_hour', 'predict_date_time', 'forecasted_temp', 'forecast_lat', 'forecast_long']
historical_preds.columns = cols
historical_preds.head()

Index(['gfs_init_utc', 'forecast_hour', 'valid_time_utc', 'gfs_temp_f',
       'gfs_grid_lat', 'gfs_grid_lon'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 930 entries, 0 to 929
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   gfs_init_utc    930 non-null    datetime64[ns]
 1   forecast_hour   930 non-null    int64
 2   valid_time_utc  930 non-null    object
 3   gfs_temp_f      930 non-null    float64
 4   gfs_grid_lat    930 non-null    float64
 5   gfs_grid_lon    930 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 43.7+ KB

,forecast_date,forecast_hour,predict_date_time,forecasted_temp,forecast_lat,forecast_long
0,2021-09-16 18:00:00,10,2021-09-17 04:00:00,72.949989,36.0,281.25
1,2021-09-16 18:00:00,11,2021-09-17 05:00:00,71.714247,36.0,281.25
2,2021-09-16 18:00:00,12,2021-09-17 06:00:00,71.451069,36.0,281.25
3,2021-09-16 18:00:00,13,2021-09-17 07:00:00,69.781917,36.0,281.25
4,2021-09-16 18:00:00,14,2021-09-17 08:00:00,69.460841,36.0,281.25

At this point, we have a dataset with all the forecasted temperatures for the past few years over the given dates. What we need now is to add a feature with the actual temperatues. And make a X_test dataset with predicted temperatures for 2026 and y_test with actual temperatures for 2026.

In [47]:
# making X_test dataset (predicted temperatures for 2026)

preds_2026 = csv_read("/Users/jothigupta/sem_1/AIPI 520/weather-prediction-RDU/data/raw/NOAA_GFS_FORECAST_FUTURE.csv")
preds_2026.columns = cols
preds_2026.head()

,forecast_date,forecast_hour,predict_date_time,forecasted_temp,forecast_lat,forecast_long
0,2026-09-16 18:00:00,10,2026-09-17 04:00:00,69.389924,36.0,281.25
1,2026-09-16 18:00:00,11,2026-09-17 05:00:00,68.854451,36.0,281.25
2,2026-09-16 18:00:00,12,2026-09-17 06:00:00,67.350587,36.0,281.25
3,2026-09-16 18:00:00,13,2026-09-17 07:00:00,66.622139,36.0,281.25
4,2026-09-16 18:00:00,14,2026-09-17 08:00:00,65.846943,36.0,281.25